
# [phases.setup]
# commands = ["chown -R www-data /app", "chmod -R 777 /app"]


# "php-fpm.conf" = '''
# [www]
# listen = 127.0.0.1:9000
# user = www-data
# group = www-data
# listen.owner = www-data
# listen.group = www-data
# pm = dynamic
# pm.max_children = 50
# pm.min_spare_servers = 4
# pm.max_spare_servers = 32
# pm.start_servers = 18
# clear_env = no
# '''
