[phases.setup]
commands = ["composer install"]

# Применение прав доступа для веб-сервера
[phases.permissions]
commands = ["chown -R www-data:www-data /app", "chmod -R 755 /app"]

# [phases.build]
# PHP_VERSION = "8.3"
# commands = [
#     # "php -m | grep redis || sudo apt-get update && sudo apt-get install -y php-redis",
#     # "composer install --ignore-platform-req=ext-redis",
#     # Check if Redis is installed, and if not, install it
# ]

[directories]
# Указываем необходимые директории
data = "/app/wp-content/uploads"

# (Необязательно) Добавляем директории для плагинов и тем для их сохранности
plugins = "/app/wp-content/plugins"
themes = "/app/wp-content/themes"
