[phases.setup]
commands = [
  "chmod -R 0777 /app/wp-content",
  "chmod -R 0777 /app/wp-content/themes",
  "chmod -R 0777 /app/wp-content/uploads",
  "chmod -R 0777 /app/wp-content/plugins",
  "chmod -R 0777 /app/wp-content/ai1wm-backups",
  "chmod -R 0777 /app/wp-content/uploads/wp-migrate-db",
  "chown -R www-data:www-data /app/wp-content/uploads",
]
