
# [phases.install]
# commands = ["chown 1000:1000 -R /app"]

[phases.setup]
commands = ["composer install"]

# Применение прав доступа для веб-сервера
[phases.permissions]
commands = ["chown -R www-data:www-data /app", "chmod -R 755 /app"]

[phases.build]
commands = ["echo 'Build complete'"]
PHP_VERSION = "8.3"

# [phases.start]
# Запуск Nginx и PHP
# commands = ["service nginx start", "php-fpm"]

# [environment]
# Переменные окружения для WordPress
# DB_NAME = "your_database_name"
# DB_USER = "your_database_user"
# DB_PASSWORD = "your_database_password"
# DB_HOST = "your_database_host"
# WORDPRESS_DEBUG = "true"
# APP_KEY = "your_app_key"

# Использование подкаталога WordPress в случае, если нужно (замените на нужный путь)
# NIXPACKS_PHP_ROOT_DIR = "/app/public"

# Файл для маршрутизации в WordPress
# NIXPACKS_PHP_FALLBACK_PATH = "/index.php"

# PHP-версия

[directories]
# Указываем необходимые директории
data = "/app/wp-content/uploads"

# (Необязательно) Добавляем директории для плагинов и тем для их сохранности
plugins = "/app/wp-content/plugins"
themes = "/app/wp-content/themes"

# [services]
# Настройка базы данных MySQL (добавьте или измените при необходимости)
# [services.mysql]
# environment = {
#   MYSQL_DATABASE = "your_database_name",
# MYSQL_USER = "your_database_user",
# MYSQL_PASSWORD = "your_database_password",
# image = "mysql:5.7"
# MYSQL_ROOT_PASSWORD = "your_root_password"
# [services.nginx]
# Кастомизация Nginx, если есть свой конфиг
# config_path = "/app/nginx.conf"
# root_dir = "/app"
